# Generated by Django 2.1 on 2018-10-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_paid_userinfo_paid_winners_winners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paid_userinfo',
            old_name='stay',
            new_name='outsider',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='stay',
            new_name='outsider',
        ),
    ]
