# Generated by Django 2.1 on 2018-10-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20181029_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid_userinfo',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
